// <auto-generated />
using System;
using ElectronicEquipment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElectronicEquipment.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20221007110827_new db adde")]
    partial class newdbadde
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ElectronicEquipment.Models.EquipmentCategory", b =>
                {
                    b.Property<int>("EquipmentCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EquipmentCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentCategoryId");

                    b.ToTable("EquipmentCategories");
                });

            modelBuilder.Entity("ElectronicEquipment.Models.EquipmentGroup", b =>
                {
                    b.Property<int>("EquipmentGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EquipmentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentGroupId");

                    b.HasIndex("EquipmentCategoryId");

                    b.ToTable("EquipmentGroups");
                });

            modelBuilder.Entity("ElectronicEquipment.Models.Equipments", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EquipmentCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipmentGroupId")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentId");

                    b.HasIndex("EquipmentCategoryId");

                    b.HasIndex("EquipmentGroupId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ElectronicEquipment.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ElectronicEquipment.Models.EquipmentGroup", b =>
                {
                    b.HasOne("ElectronicEquipment.Models.EquipmentCategory", "EquipmentCategory")
                        .WithMany()
                        .HasForeignKey("EquipmentCategoryId");
                });

            modelBuilder.Entity("ElectronicEquipment.Models.Equipments", b =>
                {
                    b.HasOne("ElectronicEquipment.Models.EquipmentCategory", "EquipmentCategory")
                        .WithMany()
                        .HasForeignKey("EquipmentCategoryId");

                    b.HasOne("ElectronicEquipment.Models.EquipmentGroup", "EquipmentGroup")
                        .WithMany()
                        .HasForeignKey("EquipmentGroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
